name = "RotationMap"
uuid = "679ad0b4-c1ff-4e9f-b635-1f317683f6c9"
authors = ["Kenta Sato <bicycle1885@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
